### ISSUE TITLE
README.md required

### ISSUE THREAD

**Issue by ralodev** [Raul-Lopez-Cruz/Juego-2D#1]
Create a README.md for the project.

**Comment by oaxaquenadev** [comment]
Sure!

**Comment by ralodev** [comment]
<details>
<summary>You can use the following images if needed
</summary>
<img src="https://github.com/ralo-dev/DinoRun-2D/assets/93017723/324db66b-3c23-4463-a4aa-fcaa32bd1139" alt="dino-gif"/>
<img src="https://github.com/ralo-dev/DinoRun-2D/assets/93017723/ec270f05-e594-4acd-a68e-a1124e2cbf86" alt="dino-landing"/>
</details>

**Comment by oaxaquenadev** [comment]
Sorry, I didn't see your message with the attached images and I already pushed the commit.
